name: dagger
on:
  push:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v7
        with:
          call: test --source=.
          module: github.com/kpenfound/dagger-modules/golang@v0.2.0
  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v7
        with:
          call: build-container --source=. --args=. publish --address=ttl.sh/my-app-$RANDOM
          module: github.com/kpenfound/dagger-modules/golang@v0.2.0